import fs from 'fs';
import * as cheerio from 'cheerio';
const mdPath = 'C:/Users/hp/.gemini/antigravity-ide/brain/ad5d672a-e124-4985-834e-e341c97572da/.system_generated/steps/1093/content.md';
const content = fs.readFileSync(mdPath, 'utf8');
const $ = cheerio.load(content);
console.log('h2 count:', $('h2').length);
console.log('h3 count:', $('h3').length);
console.log('div.text count:', $('div.text').length);
console.log('div.article-content count:', $('div.article-content').length);
console.log('div.text-content count:', $('div.text-content').length);
console.log('article count:', $('article').length);
